version: '3.8'
services:
  web:
    build:
      context: .  # Specifies the directory containing the Dockerfile and build context
      dockerfile: web.Dockerfile  # Specifies the name of the Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - neo4j
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=hellohello
    command: ["flask", "run"]
  
  neo4j:
    build:
      context: .  # Similarly, specifies the directory containing the Dockerfile
      dockerfile: neo4j.Dockerfile  # Specifies the custom Dockerfile for Neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
      - "7473:7473"
    volumes:
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/var/lib/neo4j/plugins
      - ./neo4j/neo4j-entrypoint.sh:/neo4j-entrypoint.sh
    entrypoint: ["/bin/bash", "/neo4j-entrypoint.sh"]




